services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "${APP_PORT-8080}:${APP_PORT-8080}"
    restart: always
    environment:
      - APP_HOST=${APP_HOST:-localhost}
      - APP_PORT=${APP_PORT:-8080}
      - DB_CONNECTION=${DB_CONNECTION:-mysql://root:verysecret@db:3306/db_book_lending?parseTime=True&loc=Local}
      - SERVICE_NAME=${SERVICE_NAME:-db_book_lending}
    depends_on:
      - db
  db: 
    image: mysql:8.0
    ports:
      - "3306:3306"
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=${DB_ROOT_PASSWORD:-verysecret}
      - MYSQL_DATABASE=${DB_DATABASE:-db_book_lending}
      - MYSQL_USER=${DB_USERNAME:-user1}
      - MYSQL_PASSWORD=${DB_PASSWORD:-user1secret}
